service: fr

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: ap-northeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
        - dynamodb:ConditionCheckItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:UpdateItem
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource:
        - "*"
plugins:
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 5

package:
  artifact: dst.zip

functions:
  api:
    timeout: 30
    memorySize: 256
    handler: api.handler
    events:
      - http:
          path: /{proxy+}
          method: any

  # cron:
  #   timeout: 30
  #   memorySize: 256
  #   handler: cron.handler

resources:
  Resources:
    Uploads:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: fr-${opt:stage}-store
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "Authorization"
              AllowedMethods:
                - GET
              AllowedOrigins:
                - "*"
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - POST
              AllowedOrigins:
                - "*"