name: CI
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    container: catchfashion/microservice-ci:node14
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: npm ci
      - name: Lint
        run: npm run lint
      # - name: Deploy
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      #   run: |
      #     npm run deploy:stage
      #     npm run deploy:prod
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
